config/routes.rb
SVConverterApp::Application.routes.draw do
  root "static_pages#home"
  match '/help', to: 'static_pages#help', via: "GET" 
  match '/signup', to: 'usuarios#new', via: "GET"

  get "static_pages/home"
  
  resources :videos, only: [:new, :create, :destroy]
  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: "GET"
  match '/signout', to: 'sessions#destroy', via: "DELETE"
  match '/loaderio-1495b157ce5681d327996eba1013333c.html', :to => 'static_pages#loaderio', via: "GET"

  

end

app/models/video.rb
class Video
	include Mongoid::Document
	include Mongoid::Paperclip

  	field :nombre
  	field :usuario_id
    field :mensaje
    field :estado, type: Integer
    field :fecha_publicado
    field :created_at
    field :updated_at
    field :attach_file_name
    field :attach_content_type
    field :attach_file_size
    field :attach_updated_at
    field :nombre

	# States
	STATE_PROCESSING = 0
	STATE_CONVERTED = 1

	# Once the video is uploaded the state must be SET and
	# the 
	before_create { self.estado = STATE_PROCESSING } 
	after_create { convert_video }


	# Model configurations
	belongs_to :Usuario
	#default_scope -> { order('attach_updated_at DESC')}
	
	#validates :usuario_id, presence: true
	validates :mensaje, presence: true
	
	# For the use of gem Paperclip
	has_mongoid_attached_file :attach
	validates_attachment_presence :attach
	#validates_attachment_content_type :attach, :content_type => ['movie/quicktime','movie/avi','movie/mpg']

	def self.converted
		STATE_CONVERTED
	end
	def converted?
		return (self.estado == STATE_CONVERTED)
	end
	def self.estado_to_s(estado)
		if estado == STATE_CONVERTED
			"Publicado"
		elsif estado == STATE_PROCESSING
			"Procesando"
		else
			"ERROR DE ESTADO"
		end
	end

	def convert_video
		#Aquí va el código para colocar en la cola los mensajes en SQS 
		#@sqs = AWS::SQS.new
		#@queue = @sqs.queues.create("dev_svconverterqueue")
		#@queue.send_message(self.estado.to_s+";"+self.id+";")
		# Create an IronMQ::Client object
		@ironmq = IronMQ::Client.new(:token => "_UbrPaxqhKegRTHcB83w186P1Z8", :project_id => "5281b9309d749a0009000044")
		# Get a queue (if it doesn't exist, it will be created when you first post a message)
		@queue = @ironmq.queue("svconverter_queue")
		# Post a message
		@queue.post(self.estado.to_s+";"+self.id+";")
	end
	def process_video
		#Esto lo vamos a crear como un rake
		if self.estado == STATE_PROCESSING
			video_url = self.attach.url(nil, false)
			video_filename = self.attach.original_filename
			system("ffmpeg -i "+ video_url+ " -vcodec libx264 -strict experimental #{Rails.root}/public/system/temp/"+ video_filename[0,video_filename.size-4]+".mp4")
			converted = File.open("#{Rails.root}/public/system/temp/"+video_filename[0,video_filename.size-4]+".mp4")
			self.attach = converted
			converted.close
			File.delete("#{Rails.root}/public/system/temp/"+video_filename[0,video_filename.size-4]+".mp4")
			self.estado = STATE_CONVERTED
			self.fecha_publicado = Time.zone.now
			self.save!
		end
	end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :destroy]
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.paginate(page: params[:page], per_page: 2, order: 'nombre ASC')
 
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    # Esta solución no es viable con la versión de Dynamoid 0.7.1
    @video = current_user.videos.create(video_params)
    @video.usuario_id = current_user.id
    respond_to do |format|
      if @video.save
        flash[:success] = "El video ha sido posteado, pasarán unos segundos para ser publicado"
        format.html { redirect_to current_user }
        format.json { render action: 'show', status: :created, location: @video }
      else
        puts @video.to_s
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  def convertirPrueba
    videoConverter = Video.new
    #Falta crear una instancia válida de un video para poder hacer el delayed job
    videoConverter.delay.process_video    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:nombre, :mensaje, :attach, :attach_file_name)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="row">
  <div class="span6 offset3">
  <%= form_for @video do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :mensaje %><br>
    <%= f.text_field :mensaje %>
  </div>
  <div class="field">
    <%= f.file_field :attach %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
</div>
<% end %>

app/views/videos/_video.html.erb
<!--- Codigo para mostrar los videos -->
<div class="content">
<div class="row">
<div class="span6">

	<% if video.converted? %>

	<video id="myElement<%= video.id %>" class="video-js vjs-default-skin vjs"
	controls preload="auto" width="420" height="280"
	data-setup='{"example_option":true}'>
	<source src="<%= video.attach.url%>" type='video/mp4' />
	</video>
         <%else%>
            <img src= "/loading.gif" width="420" height="280">
        <% end %>
    </div> 


 	<div class="span4">
			<span class="content">
				<b>Nombre:</b> <%= video.nombre %><br>
				<b>Mensaje:</b> <%= video.mensaje %><br>
				<b>Usuario: </b> <%= Usuario.find(video.usuario_id).email %><br>
				<b>Estado:</b> <font color="red"><%= Video.estado_to_s(video.estado) %></font><br>
			</span>
			<span class="timestamp">
				<b>Creado:</b> <%= video.attach_updated_at %><br>
			</span>
			<% if !video.fecha_publicado.nil? %>
			<span class="timestamp">
				<b>Publicado:</b> <%= video.fecha_publicado %><br>
			</span>
			<% end %>
	</div>
</div>
</div>
<br><hr>
<!--- Codigo para mostrar los videos -->

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', root_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Usuario</th>
      <th>Fecha upload</th>
      <th>Mensaje</th>
      <th>Estado</th>
      <th>Fecha publicado</th>
      <th>Ruta</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.nombre %></td>
        <td><%= video.usuario_id %></td>
        <td><%= video.fecha_upload %></td>
        <td><%= video.mensaje %></td>
        <td><%= video.estado %></td>
        <td><%= video.fecha_publicado %></td>
        <td><%= video.ruta %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>Subir un nuevo video</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @video.nombre %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @video.usuario_id %>
</p>

<p>
  <strong>Fecha upload:</strong>
  <%= @video.fecha_upload %>
</p>

<p>
  <strong>Mensaje:</strong>
  <%= @video.mensaje %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @video.estado %>
</p>

<p>
  <strong>Fecha publicado:</strong>
  <%= @video.fecha_publicado %>
</p>

<p>
  <strong>Ruta:</strong>
  <%= @video.ruta %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>