config/routes.rb
SVConverterApp::Application.routes.draw do
  root "static_pages#home"
  match '/help', to: 'static_pages#help', via: "GET" 
  match '/signup', to: 'usuarios#new', via: "GET"

  get "static_pages/home"
  
  resources :videos, only: [:new, :create, :destroy]
  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: "GET"
  match '/signout', to: 'sessions#destroy', via: "DELETE"
  match '/loaderio-1495b157ce5681d327996eba1013333c.html', :to => 'static_pages#loaderio', via: "GET"

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Oscar Kiyoshige Garces - Santiago Villaveces
	</small>

	<nav>
		<ul class = "nav pull-right">
			<li> <%= link_to "Home", root_path %> </li>
				<li> <%= link_to "Help", help_path %> </li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<%= link_to "SVConverter app", '#', id: "logo" %>
					<nav>
						<ul class = "nav pull-right">
							<li> <%= link_to "Home", root_path %> </li>
							<li> <%= link_to "help", help_path %> </li>
							<% if signed_in? %>
								<li> <%= link_to "Usuarios", usuarios_path %></li>
								<li id="fat-menu" class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Cuenta<b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li><%= link_to "Perfil", current_user %></li>
										<!--<li><%= link_to "Config.", edit_usuario_path(current_user) %></li>-->
										<li><%= link_to "Nuevo Video", new_video_path %> 
										<li class="divider"></li>
										<li>
											<%= link_to "Sign out", signout_path, method: "DELETE" %>
										</li>
									</ul>
								</li>
								<% else %>
								<li> <%= link_to "Sign in", signin_path %> </li>
							<% end %>
						</ul>
					</nav>
				</div>
			</div>
		</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Video Converter | <%=yield(:title)%> </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container"> 
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %> </div>
			<% end %>
			<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
	</body>
</html>